# File: docker-stack.yml
version: '3.8'

services:
  app:
    image: e-katalog-umkm:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - app-network
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: e_katalog_umkm
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - app-network

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  dbdata:
