version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      # Mount volume untuk sharing dengan nginx
      - app_data:/var/www
    depends_on:
      - db
    networks:
      - laravel
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    # Tambahkan command untuk copy files ke volume
    command: >
      sh -c "
        cp -r /var/www/* /tmp/app_files/ 2>/dev/null || cp -r /var/www/. /tmp/app_files/ &&
        rm -rf /var/www/* &&
        cp -r /tmp/app_files/* /var/www/ &&
        chown -R www-data:www-data /var/www &&
        php-fpm
      "

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - app_data:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
  app_data:
    driver: local
